### ISSUE TITLE
Trouver une mise en page pour les projets

### ISSUE THREAD

**Issue by Herondil** [LatrachNassim/Portofolio_nassim#11]
https://wireframe.cc/

**Comment by LatrachNassim** [comment]
https://emanuelemilella.com/works

**Comment by LatrachNassim** [comment]
https://latyr.dev/

**Comment by LatrachNassim** [comment]
Fusionner la page compétence et projet. Faire un jauge normal avec un symbole(rond, étoile) remplit pour maitrise non remplit pour non maitrisé pour donner un pourcetage de t maitrise total sur la cométence et donner les projets ce lequel tu as utilisé la compétence choisit.

**Comment by Herondil** [comment]
Maintenant que les références sont trouvées, il ne manque plus qu'un plan réalisé avec wireframe.cc !

**Comment by Herondil** [comment]
Ajout du slider !

**Comment by Herondil** [comment]
Quel résultat sur tablette ou tel ?

**Comment by Herondil** [comment]
Trop d'espace vide en portrait sur Mobile

**Comment by LatrachNassim** [comment]
![IMG_20200629_115938252](https://user-images.githubusercontent.com/43538289/87922208-f21d0e00-ca7b-11ea-9216-cbd119d0c3d6.jpg)

Idée de la responsive de la page contact

**Comment by LatrachNassim** [comment]
Bug de la page projet sur mobile. Faire disparaitre les projets version mobile sur les écrans d'ordi et de tablette

**Comment by LatrachNassim** [comment]
Finalisation de la page projet. Les objectifs ont été atteint.
