### ISSUE TITLE
Trouver une mise en page pour "contact"

### ISSUE THREAD

**Issue by Herondil** [LatrachNassim/Portofolio_nassim#12]

**Comment by LatrachNassim** [comment]
![image](https://user-images.githubusercontent.com/43538289/76844487-a47a6580-683d-11ea-85dd-97fe498a5451.png)

**Comment by Herondil** [comment]
Il faut regarder aussi ce qu'il est possible de faire avec formspree, https://formspree.io/

**Comment by LatrachNassim** [comment]
https://formspree.io/ à utiliser pour la page contact.

**Comment by Herondil** [comment]
La map n'est pas adapté en mode portrait sur mobile

**Comment by LatrachNassim** [comment]
Créer un schéma
![image](https://user-images.githubusercontent.com/43538289/88526122-cf4ea480-cffb-11ea-8ca8-472066d812e5.png)
